# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='phone_number',
            field=models.CharField(default=917610002521, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
